### ISSUE TITLE
Issue with Inventory

### ISSUE THREAD

**Issue by BlacKKyFR** [qqqwda/pokemeow-autoplay#12]
![image_2024-05-19_073959444](https://github.com/qqqwda/pokemeow-autoplay/assets/162887930/a0e6058e-cd8a-43da-bbe1-17d722a91499)

[32m05/17/2024 08:17:18 PM - [BlacKK] - Checking second page of inventory...[0m
[31m05/17/2024 08:17:19 PM - [BlacKK] - An error occurred while getting the inventory JSON: invalid literal for int() with base 10: 'X'[0m
[32m05/17/2024 08:17:19 PM - [BlacKK] - ❌Failed to get inventory.[0m

There seems to be an error with the inventory due to the mega bracelet which returns a value of X. This results in the bot no longer executing the ';quest' command.

**Comment by qqqwda** [comment]
Hey, sorry about the inconvenience, I'll be fixing this when I return home on Monday/Tuesday

**Comment by qqqwda** [comment]
@BlacKKyFR can you test again? make sure the version is 1.51
![image](https://github.com/qqqwda/pokemeow-autoplay/assets/41929135/6bfa3559-8555-4a63-917b-b2c93997849d)

**Comment by BlacKKyFR** [comment]
![image](https://github.com/qqqwda/pokemeow-autoplay/assets/162887930/6e378777-fb0f-49d9-a251-6f2a817b3840)
It's okay for me , thanks you !

**Comment by BlacKKyFR** [comment]
thanks you !
