### ISSUE TITLE
Feature proposal

### ISSUE THREAD

**Issue by BlacKKyFR** [qqqwda/pokemeow-autoplay#13]
Hello, I am not sure if this will be relevant, but having the option to choose the language in which the script returns information or even for screenshots and other features would be great. Of course, this would be with the help of a volunteer for the language part. I can assist with translations into French myself. However, if this proposal doesn't interest you but you are open to suggestions, I might have other ideas. :)

**Comment by qqqwda** [comment]
that seems like a lot of work 🤔
do you want to translate even the name of the pokemons?

**Comment by BlacKKyFR** [comment]
So, for the Pokémon names, I don't think it's necessary because it would require a lot of work. You would need to do something like "Squirtle = Carapuce," and given the number of Pokémon, it would take an extremely long time. No, I was thinking more about items, rarities, and other things. But if you have the courage for the Pokémon names, we can do it, but it will take a long time.

**Comment by qqqwda** [comment]
Here you can find the translations of the pokemons, but I think there is no way to differentiate one pokemon from another https://github.com/sindresorhus/pokemon/tree/main

**Comment by BlacKKyFR** [comment]
Yes, with that you have the list in French, you would just need to do something like "Squirtle = Carapuce," I imagine.

**Comment by BlacKKyFR** [comment]
I have other proposal ideas. Should I note them here, create them, or would you prefer to discuss them via message on Discord (my spoken English isn't great)? For this one, should I include what I see that can be translated at a minimum? To activate a language other than English, we can include Language = English in run_account_example.
