### ISSUE TITLE
issue or feature ? with explore

### ISSUE THREAD

**Issue by BlacKKyFR** [qqqwda/pokemeow-autoplay#14]
Hello, it's me again :) Is it possible to set up an automatic deactivation of the exploration once the exploration limit message is reached?
[31m05/23/2024 08:34:25 PM - [BlacKK] - 🗺️ Something happened...[0m
[31m05/23/2024 08:34:25 PM - [BlacKK] - @Luka
;explore grass
PokéMeow
APP
Aujourd’hui à 20:34
Uh oh! You have reached the daily ;explore limit! The beta test allows for 4,000 steps per day.
The limit will reset on 24 mai 2024 06:00[0m

**Comment by qqqwda** [comment]
can you check again using the latest version **1.52**?

**Comment by BlacKKyFR** [comment]
![image](https://github.com/qqqwda/pokemeow-autoplay/assets/162887930/fb870197-00a5-42da-bb11-d316fc4cb5da)
![image](https://github.com/qqqwda/pokemeow-autoplay/assets/162887930/841242dc-328d-4212-8303-46e361dae174)
![image](https://github.com/qqqwda/pokemeow-autoplay/assets/162887930/ed0299d2-e695-4482-90ea-6cf4f221fc45)
It seems to be working, but the script restarts too quickly after deactivating the explore feature, which creates a crash due to the latency between the bot and PokéMeow. After that, it still works, so it's okay. Thanks
