### ISSUE TITLE
Logo for you script 

### ISSUE THREAD

**Issue by BlacKKyFR** [qqqwda/pokemeow-autoplay#16]
![Prototype](https://github.com/qqqwda/pokemeow-autoplay/assets/162887930/d4bca439-1951-47df-a793-1a4c7ff61baa)
Hello, here is a small logo for your script so I don't know if you will be able to integrate it somewhere but here it is as a gift to thank you, if ever there are details or another idea that you would like, don't hesitate.
I put Auto Meow rather than pokemeow-autoplay, it was more aesthetic and nice. 1024*1024 pixel

**Comment by qqqwda** [comment]
thats amazing bro, ill see what i can do with the logo
thanks for the support ! ❤️

**Comment by BlacKKyFR** [comment]
I'm glad you like it😁
