### ISSUE TITLE
Resets itself after every fish Caught

### ISSUE THREAD

**Issue by Tr3asurenub** [qqqwda/pokemeow-autoplay#18]
Seems like everytime i catch a fish the bot gives me an error code then resets itself by saying "Continuing to play" Delaying my bot for a good 15 seconds each time i catch a fish. Started happening out of nowhere. here is the error:

![Pokemeow fish error](https://github.com/qqqwda/pokemeow-autoplay/assets/173347929/3d945dd3-b2da-4d64-8ed5-897599874e37)

I never edited any files aside from the ./bat file to enable/disable fishing

I blurred out my Username in the files hence is why its censored.

**Comment by qqqwda** [comment]
I'll be fixing this soon, I think I know the reason of this error

**Comment by qqqwda** [comment]
@Tr3asurenub download the latest version on Develop branch and retry please, let me know if you find any error 🙏

**Comment by Tr3asurenub** [comment]
> @Tr3asurenub download the latest version on Develop branch and retry please, let me know if you find any error 🙏

Sry been working a lot so i havent had the chance to test it until now. So far i haven't had the issue with fishing and it seems a bit more responsive as of now.

Though a bigger issue now is that it can no longer sucessfully send the captcha pictures to the website to get past them. Though i do have an image of the error it gives which i will post below

![pokemeow bot trouble 2](https://github.com/qqqwda/pokemeow-autoplay/assets/173347929/70c103cf-1f51-47f5-a16c-9444acf07ee2)

Though it's weird because sometimes that issue happens and someTimes it works just fine.
