### ISSUE TITLE
RapidAPI Sometimes not sending response

### ISSUE THREAD

**Issue by Tr3asurenub** [qqqwda/pokemeow-autoplay#19]
Howdy, There seems to be another bug issue i keep having. I gotta watch the bot as it hunts and fishes for whenever the captcha pops up. And when it does sometimes it won't send a response and time itself out, leaving me to have to jump in and complete it so i dont get banned. I will post a picture below:

[
![pokemeow bot trouble 2](https://github.com/qqqwda/pokemeow-autoplay/assets/173347929/19c89ec6-a46f-436b-8461-022829809644)
](url)

**Comment by qqqwda** [comment]
try installing local captcha, in readme you can find the instructions

**Comment by Tr3asurenub** [comment]
The new one you added? Yeah ive tried to make an attempt to. Keeps telling me im missing a program called "Tensorflow" which in this case is labeled as a ".whl" file which apparently i need the program "Pip" for which is basically impossible to install by all means, or at least idk how to install that confusing shit.


![Tensorflow error](https://github.com/qqqwda/pokemeow-autoplay/assets/173347929/2d360593-6054-4e61-a5e0-e30ebc26d006)


***UPDATE***
Managed To get everything installed but it still won't register the fact that tensorflowe is installed which keeps giving me the error above. I also can't seem to connect to localhost as it just redirects to an error page.

***Update 2.0***

Managed To get everything working.
