### ISSUE TITLE
Battle config

### ISSUE THREAD

**Issue by LLL184** [qqqwda/pokemeow-autoplay#23]
Is there any way for me to change the battle to another npc?

**Comment by qqqwda** [comment]
in **bot.py** line 34 file you can find the task that executes the battle command:

`self.battle_task = Task(lambda: self.battle.start(";b npc 1"), lambda: random.randint(39, 42))`

just change ";b npc 1" to any npc you want, [⚠️](https://emojipedia.org/warning)**remember that this Task just spams the first attack button**.[⚠️](https://emojipedia.org/warning)

**Comment by LLL184** [comment]
thanks bro!
